# Generated by Django 4.1.4 on 2022-12-09 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('M', 'Mentor'), ('E', 'Expert'), ('I', 'Investor')], max_length=1)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('cv', models.FileField(blank=True, null=True, upload_to='users/Card_Profile/cv', verbose_name='Резюме')),
                ('specialization', models.ManyToManyField(blank=True, null=True, to='users.specialization', verbose_name='Специализация')),
            ],
        ),
        migrations.CreateModel(
            name='StartUp_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='Название стартапа')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('needed_to', models.TextField(null=True, verbose_name='Что нужно для реализации')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='users/StartUp_Profile/logo', verbose_name='Логотип')),
                ('presentation', models.FileField(null=True, upload_to='users/StartUp_Profile/presentation', verbose_name='Презентация')),
                ('idea', models.TextField(null=True, verbose_name='Идея стартап проекта')),
                ('specialization', models.ManyToManyField(null=True, to='users.specialization', verbose_name='Специализация')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='location_lat',
            field=models.FloatField(null=True, verbose_name='Локация X'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_lon',
            field=models.FloatField(null=True, verbose_name='Локация Y'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile/photo', verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.card_profile', verbose_name='Стартап проект')),
                ('start_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.startup_profile', verbose_name='Стартап проект')),
            ],
        ),
    ]
