# Generated by Django 4.1.4 on 2022-12-09 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_card_profile_startup_profile_profile_location_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_profile',
            name='create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='card_profile',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменил'),
        ),
        migrations.AddField(
            model_name='profile',
            name='activate',
            field=models.BooleanField(blank=True, default=True, verbose_name='Бот активен?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='profile',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменил'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='startup_profile',
            name='create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='startup_profile',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменил'),
        ),
        migrations.AddField(
            model_name='team',
            name='create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='team',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.card_profile', verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='SeeStartUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Посмотрел')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Пользователь')),
                ('start_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed', to='users.startup_profile', verbose_name='Стартап проект')),
            ],
        ),
    ]
