# Generated by Django 4.1.4 on 2022-12-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_card_profile_create_card_profile_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=80, null=True, verbose_name='Имя пользователя ТГ'),
        ),
    ]
