# Generated by Django 4.1.4 on 2022-12-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_profile',
            name='specialization',
            field=models.ManyToManyField(blank=True, to='users.specialization', verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Локация X'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Локация Y'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='startup_profile',
            name='specialization',
            field=models.ManyToManyField(to='users.specialization', verbose_name='Специализация'),
        ),
    ]
