# Generated by Django 4.1.4 on 2022-12-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_secret_link_profile_secret_link_datetime'),
    ]

    operations = [
    ]
