# Generated by Django 4.1.4 on 2022-12-10 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_secret_link'),
    ]

    operations = [
    ]
