# Generated by Django 4.1.4 on 2022-12-10 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_startup_profile_options_datingcard_startup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card_profile',
            options={'verbose_name': 'Карта профиля', 'verbose_name_plural': 'Карты профиля'},
        ),
        migrations.AddField(
            model_name='card_profile',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Профиль'),
        ),
    ]
