# Generated by Django 4.1.4 on 2022-12-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_card_profile_options_card_profile_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datingcard_startup',
            options={'verbose_name': 'Матч', 'verbose_name_plural': 'Матчи'},
        ),
        migrations.AddField(
            model_name='datingcard_startup',
            name='match_profile_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datingcard_startup',
            name='match_start_up_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
