# Generated by Django 4.1.4 on 2022-12-11 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_datingcard_startup_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seestartup',
            options={'verbose_name': 'Просмотреный стартап', 'verbose_name_plural': 'Просмотренные стартапы'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterField(
            model_name='card_profile',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='users.profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='card_profile',
            name='role',
            field=models.CharField(choices=[('M', 'Ментор'), ('E', 'Эксперт'), ('I', 'Инвестор')], max_length=1),
        ),
        migrations.AlterField(
            model_name='datingcard_startup',
            name='match_profile',
            field=models.BooleanField(default=False, verbose_name='Профиль лайкнул стартап'),
        ),
        migrations.AlterField(
            model_name='datingcard_startup',
            name='match_start_up',
            field=models.BooleanField(default=False, verbose_name='Стартап лайкнул профиль'),
        ),
        migrations.CreateModel(
            name='SeeCardProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Посмотрел')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewedCard', to='users.card_profile', verbose_name='Профиль пользователя')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Просмотреный стартап',
                'verbose_name_plural': 'Просмотренные стартапы',
            },
        ),
    ]
