# Generated by Django 4.1.4 on 2022-12-15 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_seestartup_options_alter_team_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seecardprofile',
            options={'verbose_name': 'Просмотреный карты профиля', 'verbose_name_plural': 'Просмотренные карты профиля'},
        ),
        migrations.AlterField(
            model_name='startup_profile',
            name='ceo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startUp_user', to='users.profile', verbose_name='Организатор'),
        ),
    ]
