# Generated by Django 4.1.4 on 2022-12-17 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_seecardprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup_profile',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('value', models.IntegerField(verbose_name='Значение')),
                ('create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Посмотрел')),
                ('start_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment', to='users.startup_profile', verbose_name='Стартап проект')),
            ],
            options={
                'verbose_name': 'Инвестиции',
                'verbose_name_plural': 'Инвестиции',
            },
        ),
    ]
